# Generated by Django 4.2.20 on 2025-04-23 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('file_types', models.JSONField()),
                ('max_files', models.IntegerField(default=3)),
                ('file_pattern', models.CharField(blank=True, max_length=255, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paths', to='client_manager.client')),
            ],
        ),
        migrations.CreateModel(
            name='OutputConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(max_length=10)),
                ('output_dir', models.CharField(max_length=255)),
                ('filename_template', models.CharField(max_length=255)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='output_configs', to='client_manager.client')),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='output_configs', to='client_manager.path')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='output_configs', to='client_manager.task')),
            ],
        ),
    ]
