# Generated by Django 4.2.20 on 2025-04-25 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='sftp_host',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='sftp_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='sftp_port',
            field=models.IntegerField(blank=True, default=22, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='sftp_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
