# Generated by Django 4.2.20 on 2025-04-28 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_manager', '0003_downloadedfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloadedfile',
            name='file',
        ),
        migrations.AddField(
            model_name='downloadedfile',
            name='file_content',
            field=models.BinaryField(default=b'', null=True),
        ),
    ]
