# Generated by Django 4.2.20 on 2025-04-29 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_manager', '0004_remove_downloadedfile_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadedfile',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='downloadedfile',
            name='sent_to_sftp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='downloadedfile',
            name='validation_errors',
            field=models.TextField(blank=True, null=True),
        ),
    ]
