# Generated by Django 4.2.20 on 2025-05-09 10:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('client_manager', '0005_downloadedfile_is_validated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='description',
        ),
        migrations.AddField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='client',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='sftp_port',
            field=models.IntegerField(default=22),
        ),
        migrations.CreateModel(
            name='FileConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('accumulator', 'Accumulator'), ('eligibility', 'Eligibility')], max_length=20)),
                ('remote_path', models.CharField(max_length=255)),
                ('file_pattern', models.CharField(max_length=255)),
                ('local_path', models.CharField(max_length=255)),
                ('renamed_pattern', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_configs', to='client_manager.client')),
            ],
        ),
    ]
